/**
 * ROK-1374 — the reversible GAME pick, end to end (spec "Pick" scenarios 7–9,
 * as corrected by LEAD CORRECTION 2026-09-05: the pick is a GAME, not a mode).
 *
 * Covers AC14 (reversible until the advance fires, 409 after) and AC15 (the
 * lineup CREATOR on role `member` may pick; a plain roster voter may not;
 * `/dismiss` and `/resolve` stay operator-only).
 *
 * CANNOT RUN YET — migration `0169_lineup_tie_hold` is generated by the Lead
 * after the lanes merge, and every assertion below reads a `tie_*` column.
 *
 * REGRESSION RECIPE for the Lead, one per case, each must fail on its own
 * expectation and NEVER by timeout:
 *   - "creator picks": delete the pick write in `tie-pick.helpers.ts::pickTieGame`
 *     → `tiePickGameId` assertion fails with `Received: null`.
 *   - "creator picks": delete `armGraceWindow(...)` → `pendingAdvanceAt`
 *     assertion fails with `Received: null` and the job lookup returns falsy.
 *   - "voter is refused": delete `assertCanPickTiebreaker(lineup, user)` from
 *     `pickTieGame` → status assertion fails `Expected: 403, Received: 200`.
 *   - "undo": delete the column clear in `undoTiePick` → `Received: <gameId>`.
 *   - "the grace job decides the picked game": revert the `lineup.tiePickGameId`
 *     branch in `lineup-phase.processor.ts::processGraceAdvance` → status stays
 *     `voting`, so the assertion fails `Expected: "decided", Received: "voting"`.
 *   - "undo after decided": change the `status !== 'voting'` guard in
 *     `undoTiePick` → `Expected: 409, Received: 200`.
 */
import { getQueueToken } from '@nestjs/bullmq';
import type { Queue } from 'bullmq';
import { and, eq } from 'drizzle-orm';
import { getTestApp, type TestApp } from '../common/testing/test-app';
import {
  truncateAllTables,
  loginAsAdmin,
  waitFor,
} from '../common/testing/integration-helpers';
import * as schema from '../drizzle/schema';
import { SETTING_KEYS } from '../drizzle/schema/app-settings';
import { SettingsService } from '../settings/settings.service';
import { createMemberAndLogin } from '../events/signups.integration.spec-helpers';
import { LineupPhaseQueueService } from './queue/lineup-phase.queue';
import {
  LINEUP_PHASE_QUEUE,
  LINEUP_PHASE_TRANSITION,
} from './queue/lineup-phase.constants';
import { LineupPhaseProcessor } from './queue/lineup-phase.processor';

type LineupRow = typeof schema.communityLineups.$inferSelect;
type Response = { status: number; body: unknown };

/** Long enough that the real worker cannot fire mid-assertion. */
const LONG_GRACE_MS = 300_000;
/** Ceiling for the activity-log write that trails the transition. */
const LOG_DEADLINE_MS = 10_000;

let testApp: TestApp;
let adminToken: string;
let settings: SettingsService;
let phaseQueue: LineupPhaseQueueService;
let rawQueue: Queue;

beforeAll(async () => {
  testApp = await getTestApp();
  adminToken = await loginAsAdmin(testApp.request, testApp.seed);
  settings = testApp.app.get(SettingsService);
  phaseQueue = testApp.app.get(LineupPhaseQueueService);
  rawQueue = testApp.app.get<Queue>(getQueueToken(LINEUP_PHASE_QUEUE));
});

afterEach(async () => {
  await settings.delete(SETTING_KEYS.LINEUP_AUTO_ADVANCE_GRACE_MS);
  testApp.seed = await truncateAllTables(testApp.db);
  adminToken = await loginAsAdmin(testApp.request, testApp.seed);
});

// ─── fixture helpers (copied from lineup-tie-hold.integration.spec.ts) ───────

/** A fixture step that fails loudly names ITSELF — never a downstream timeout. */
function expectOk(res: Response, step: string): void {
  if (res.status >= 300) {
    throw new Error(
      `fixture step "${step}" failed: HTTP ${res.status} ${JSON.stringify(res.body)}`,
    );
  }
}

function createPrivateLineup(
  token: string,
  inviteeUserIds: number[],
  votesPerPlayer: number,
) {
  return testApp.request
    .post('/lineups')
    .set('Authorization', `Bearer ${token}`)
    .send({
      title: 'Tie Pick Test',
      visibility: 'private',
      inviteeUserIds,
      votesPerPlayer,
    });
}

async function createGames(count: number) {
  const games: (typeof schema.games.$inferSelect)[] = [];
  for (let i = 0; i < count; i++) {
    const [game] = await testApp.db
      .insert(schema.games)
      .values({
        name: `Tie Pick Game ${i + 1}`,
        slug: `tie-pick-game-${i + 1}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      })
      .returning();
    games.push(game);
  }
  return games;
}

function nominate(token: string, lineupId: number, gameId: number) {
  return testApp.request
    .post(`/lineups/${lineupId}/nominate`)
    .set('Authorization', `Bearer ${token}`)
    .send({ gameId });
}

function vote(token: string, lineupId: number, gameId: number) {
  return testApp.request
    .post(`/lineups/${lineupId}/vote`)
    .set('Authorization', `Bearer ${token}`)
    .send({ gameId });
}

function advanceToVoting(lineupId: number, token: string) {
  return testApp.request
    .patch(`/lineups/${lineupId}/status`)
    .set('Authorization', `Bearer ${token}`)
    .send({ status: 'voting' });
}

/** ROK-1296: the per-voter quorum gate closes on an explicit submit. */
async function submitVotes(lineupId: number, tokens: string[]): Promise<void> {
  for (const t of tokens) {
    const res = await testApp.request
      .post(`/lineups/${lineupId}/submit-votes`)
      .set('Authorization', `Bearer ${t}`)
      .send({});
    expectOk(res, 'submit votes');
  }
}

async function readLineup(lineupId: number): Promise<LineupRow> {
  const [row] = await testApp.db
    .select()
    .from(schema.communityLineups)
    .where(eq(schema.communityLineups.id, lineupId));
  if (!row) throw new Error(`lineup ${lineupId} vanished`);
  return row;
}

function getGraceJob(lineupId: number) {
  return rawQueue.getJob(`lineup-grace-${lineupId}`);
}

/** Cancel the queued job and run the grace branch by hand, as REWORK-4 does. */
async function driveGraceJobByHand(lineupId: number): Promise<void> {
  await phaseQueue.cancelGraceAdvance(lineupId);
  const processor = testApp.app.get<
    LineupPhaseProcessor,
    { processGraceAdvance(id: number): Promise<void> }
  >(LineupPhaseProcessor);
  await processor.processGraceAdvance(lineupId);
}

/** Run the deadline job by hand — the path a passed voting deadline takes. */
async function driveDeadlineByHand(lineupId: number): Promise<void> {
  const processor = testApp.app.get(LineupPhaseProcessor);
  await processor.process({
    name: LINEUP_PHASE_TRANSITION,
    data: { lineupId, targetStatus: 'decided' },
  } as never);
}

function pick(token: string, lineupId: number, gameId: number) {
  return testApp.request
    .post(`/lineups/${lineupId}/tiebreaker/pick`)
    .set('Authorization', `Bearer ${token}`)
    .send({ gameId });
}

function undoPick(token: string, lineupId: number) {
  return testApp.request
    .post(`/lineups/${lineupId}/tiebreaker/pick/undo`)
    .set('Authorization', `Bearer ${token}`)
    .send({});
}

interface TiedFixture {
  lineupId: number;
  gameIds: [number, number];
  creator: { userId: number; token: string };
  voter: { userId: number; token: string };
}

/**
 * The operator scenario with a NON-OPERATOR creator (AC15): member C creates
 * the lineup and member V is the only other voter. Two games, one vote each,
 * both submitted, grace job driven — the lineup ends parked on a tie hold.
 */
async function arrangeTiedVoting(): Promise<TiedFixture> {
  await settings.set(
    SETTING_KEYS.LINEUP_AUTO_ADVANCE_GRACE_MS,
    String(LONG_GRACE_MS),
  );
  const creator = await createMemberAndLogin(
    testApp,
    'tie-pick-creator',
    'tie-pick-creator@test.local',
  );
  const voter = await createMemberAndLogin(
    testApp,
    'tie-pick-voter',
    'tie-pick-voter@test.local',
  );
  // `POST /lineups` is operator-only, so the row is created by the admin and
  // ownership is handed to the MEMBER at the row — `created_by` is the only
  // place it lives, and it is what AC15's "creator on role member" tests.
  const created = await createPrivateLineup(adminToken, [voter.userId], 1);
  expectOk(created, 'create lineup as operator');
  const lineupId = (created.body as { id: number }).id;
  await testApp.db
    .update(schema.communityLineups)
    .set({ createdBy: creator.userId })
    .where(eq(schema.communityLineups.id, lineupId));
  const [a, b] = await createGames(2);
  expectOk(await nominate(creator.token, lineupId, a.id), 'nominate game A');
  expectOk(await nominate(voter.token, lineupId, b.id), 'nominate game B');
  expectOk(await advanceToVoting(lineupId, adminToken), 'advance to voting');
  expectOk(await vote(creator.token, lineupId, a.id), 'creator votes A');
  expectOk(await vote(voter.token, lineupId, b.id), 'voter votes B');
  return { lineupId, gameIds: [a.id, b.id], creator, voter };
}

async function expectHeld(lineupId: number, step: string): Promise<void> {
  const held = await readLineup(lineupId);
  if (held.tieDetectedAt === null) {
    throw new Error(`fixture step "${step}" failed: tieDetectedAt is null`);
  }
}

/** The grace path: everyone submitted, the grace re-check finds the tie. */
async function arrangeArmedTieHold(): Promise<TiedFixture> {
  const fixture = await arrangeTiedVoting();
  await submitVotes(fixture.lineupId, [
    fixture.creator.token,
    fixture.voter.token,
  ]);
  await driveGraceJobByHand(fixture.lineupId);
  await expectHeld(fixture.lineupId, 'arm tie hold (grace)');
  return fixture;
}

/** The deadline path: nobody submitted; the deadline closes the vote tied. */
async function arrangeDeadlineTieHold(): Promise<TiedFixture> {
  const fixture = await arrangeTiedVoting();
  await driveDeadlineByHand(fixture.lineupId);
  await expectHeld(fixture.lineupId, 'arm tie hold (deadline)');
  return fixture;
}

// ═══════════════════════════════════════════════════════════════════════════
// Scenario 7/8 — who may pick
// ═══════════════════════════════════════════════════════════════════════════

describe('ROK-1374 tie pick — authorisation (AC15)', () => {
  it('lets the lineup creator on role member pick a tied game and re-arms the grace window', async () => {
    const { lineupId, gameIds, creator } = await arrangeArmedTieHold();

    const res = await pick(creator.token, lineupId, gameIds[0]);

    expect(res.status).toBe(200);
    const row = await readLineup(lineupId);
    expect(row.tiePickGameId).toBe(gameIds[0]);
    expect(row.tiePickBy).toBe(creator.userId);
    expect(row.tiePickAt).not.toBeNull();
    // The pick claims the SAME grace window a ready quorum claims — that is
    // what makes it reversible and what fires the advance.
    expect(row.pendingAdvanceAt).not.toBeNull();
    expect(await getGraceJob(lineupId)).toBeTruthy();
    // Q2: picking records an intent; it does not decide.
    expect(row.status).toBe('voting');
    expect(row.decidedGameId).toBeNull();
  });

  it('refuses a plain roster voter with 403 and writes nothing', async () => {
    const { lineupId, gameIds, voter } = await arrangeArmedTieHold();

    const res = await pick(voter.token, lineupId, gameIds[0]);

    expect(res.status).toBe(403);
    const row = await readLineup(lineupId);
    expect(row.tiePickGameId).toBeNull();
    expect(row.pendingAdvanceAt).toBeNull();
  });

  it('400s when the chosen game is not one of the tied games', async () => {
    const { lineupId } = await arrangeArmedTieHold();
    const [outsider] = await createGames(1);

    const res = await pick(adminToken, lineupId, outsider.id);

    expect(res.status).toBe(400);
    expect((await readLineup(lineupId)).tiePickGameId).toBeNull();
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// Scenario 9 — reversible until the advance fires (AC14 / E7)
// ═══════════════════════════════════════════════════════════════════════════

describe('ROK-1374 tie pick — undo (AC14)', () => {
  it('clears the pick and cancels the job when undone inside the window', async () => {
    const { lineupId, gameIds, creator } = await arrangeArmedTieHold();
    expectOk(await pick(creator.token, lineupId, gameIds[0]), 'pick game A');

    const res = await undoPick(creator.token, lineupId);

    expect(res.status).toBe(200);
    const row = await readLineup(lineupId);
    expect(row.tiePickGameId).toBeNull();
    expect(row.tiePickAt).toBeNull();
    expect(row.tiePickBy).toBeNull();
    expect(row.pendingAdvanceAt).toBeNull();
    expect(await getGraceJob(lineupId)).toBeFalsy();
    // The hold itself survives — undoing a pick is not resolving the tie.
    expect(row.tieDetectedAt).not.toBeNull();
    expect(row.status).toBe('voting');
  });

  it('400s NO_PICK when there is nothing to undo', async () => {
    const { lineupId, creator } = await arrangeArmedTieHold();

    const res = await undoPick(creator.token, lineupId);

    expect(res.status).toBe(400);
  });
});

// ═══════════════════════════════════════════════════════════════════════════
// The advance — a picked tie decides; undo after it is final (E7)
// ═══════════════════════════════════════════════════════════════════════════

describe('ROK-1374 tie pick — the grace job decides the picked game', () => {
  it('lands the lineup in decided with the picked game and logs the transition', async () => {
    const { lineupId, gameIds, creator } = await arrangeArmedTieHold();
    expectOk(await pick(creator.token, lineupId, gameIds[1]), 'pick game B');

    await driveGraceJobByHand(lineupId);

    const row = await readLineup(lineupId);
    expect(row.status).toBe('decided');
    expect(row.decidedGameId).toBe(gameIds[1]);
    // No elimination mechanism was involved: no tiebreaker row was created.
    expect(row.activeTiebreakerId).toBeNull();
    // `logTransition` runs after the conditional UPDATE; poll rather than
    // assume the write has landed.
    await waitFor(
      async () => {
        const [logRow] = await testApp.db
          .select()
          .from(schema.activityLog)
          .where(
            and(
              eq(schema.activityLog.entityType, 'lineup'),
              eq(schema.activityLog.entityId, lineupId),
              eq(schema.activityLog.action, 'lineup_decided'),
            ),
          )
          .limit(1);
        expect(logRow).toBeTruthy();
      },
      LOG_DEADLINE_MS,
      100,
    );
  });

  // The first fleet run of smoke scenario 29: a tie the DEADLINE detected has
  // no submit ritual behind it, so the grace job's quorum check reported "not
  // ready" without the tie and released the pick's claim in silence.
  it('decides a pick on a DEADLINE-detected tie, where quorum never reports ready', async () => {
    const { lineupId, gameIds, creator } = await arrangeDeadlineTieHold();
    expectOk(await pick(creator.token, lineupId, gameIds[1]), 'pick game B');

    await driveGraceJobByHand(lineupId);

    const row = await readLineup(lineupId);
    expect(row.status).toBe('decided');
    expect(row.decidedGameId).toBe(gameIds[1]);
  });

  it('409s TIE_PICK_FINAL when the pick is undone after the advance fired', async () => {
    const { lineupId, gameIds, creator } = await arrangeArmedTieHold();
    expectOk(await pick(creator.token, lineupId, gameIds[0]), 'pick game A');
    await driveGraceJobByHand(lineupId);
    expect((await readLineup(lineupId)).status).toBe('decided');

    const res = await undoPick(creator.token, lineupId);

    expect(res.status).toBe(409);
    // The decision stands.
    const row = await readLineup(lineupId);
    expect(row.decidedGameId).toBe(gameIds[0]);
    expect(row.tiePickGameId).toBe(gameIds[0]);
  });

  // Review 2026-09-05 (critical): nothing ever nulled the tie columns, so a
  // pick survived an operator revert and auto-decided the re-run vote with no
  // human action in that round. The revert is `PATCH /status { voting }` from
  // `decided` — the same route as the forward step, validated as a reversion.
  it('an operator revert to voting clears the hold and the pick — the re-run vote starts clean', async () => {
    const { lineupId, gameIds, creator } = await arrangeArmedTieHold();
    expectOk(await pick(creator.token, lineupId, gameIds[0]), 'pick game A');
    await driveGraceJobByHand(lineupId);
    expect((await readLineup(lineupId)).status).toBe('decided');

    expectOk(await advanceToVoting(lineupId, adminToken), 'revert to voting');

    const row = await readLineup(lineupId);
    expect(row.status).toBe('voting');
    expect(row.tieDetectedAt).toBeNull();
    expect(row.tieExpiresAt).toBeNull();
    expect(row.tiePickGameId).toBeNull();
    expect(row.tiePickBy).toBeNull();
  });
});
