/**
 * Demo data installation steps.
 * Orchestrates the multi-step data generation and insertion process.
 */
import * as schema from '../drizzle/schema';
import type { DemoDataCountsDto } from '@raid-ledger/contract';
import type { DemoDataService } from './demo-data.service';
import {
  FAKE_GAMERS,
  CHARACTERS_CONFIG,
  ROLE_ACCOUNTS,
  getClassIconUrl,
  getEventsDefinitions,
} from './demo-data.constants';
import {
  createRng,
  generateEvents,
  generateCharacters,
  generateSignups,
} from './demo-data-generator';
import {
  buildOriginalCharValues,
  buildGeneratedCharValues,
  buildOriginalSignupValues,
  buildGeneratedSignupValues,
  dedupeByKey,
} from './demo-data-install.helpers';
import {
  buildRosterValues,
  reassignEventCreators,
} from './demo-data-roster.helpers';
import { insertSupportData } from './demo-data-support-steps';
import { generateAllData } from './demo-data-generation-steps';

/** Data generated by the deterministic PRNG. */
export type GeneratedData = ReturnType<typeof generateAllData>;

type UserRow = typeof schema.users.$inferSelect;
type EventRow = typeof schema.events.$inferSelect;
type CharRow = typeof schema.characters.$inferSelect;
type SignupRow = typeof schema.eventSignups.$inferSelect;
type GameRow = typeof schema.games.$inferSelect;

/** Run all demo data installation steps. Returns counts. */
export async function installDemoDataInner(
  svc: DemoDataService,
): Promise<DemoDataCountsDto> {
  const rng = createRng();
  const now = new Date();
  const { seedAdmin, allUsers, userByName } = await createUsers(svc);
  const allGames = await svc.database.select().from(schema.games);
  const gen = generateAllData(rng, allGames, now);
  const { events, chars, signups } = await insertEntities(
    svc,
    seedAdmin.id,
    allUsers,
    userByName,
    allGames,
    gen,
  );
  await finalizeInstall(svc, allUsers, userByName, events, allGames, gen);
  return buildCounts(allUsers, events, chars, signups, gen);
}

/** Insert events, characters, signups, and roster. */
async function insertEntities(
  svc: DemoDataService,
  seedAdminId: number,
  allUsers: UserRow[],
  userByName: Map<string, UserRow>,
  allGames: GameRow[],
  gen: GeneratedData,
) {
  const events = await insertEvents(svc, seedAdminId, allGames, gen.events);
  const chars = await insertCharacters(svc, userByName, allGames, gen.chars);
  const signups = await insertSignups(
    svc,
    events,
    allUsers,
    userByName,
    chars.charByUserGame,
    gen.signups,
  );
  await insertRoster(svc, signups, events, chars, gen, allGames);
  return { events, chars, signups };
}

/** Insert support data and reassign event creators. */
async function finalizeInstall(
  svc: DemoDataService,
  allUsers: UserRow[],
  userByName: Map<string, UserRow>,
  events: { origEvents: EventRow[]; genEvents: EventRow[] },
  allGames: GameRow[],
  gen: GeneratedData,
): Promise<void> {
  const igdbIdsByDbId = new Map(allGames.map((g) => [g.igdbId, g.id]));
  await insertSupportData(
    svc,
    userByName,
    allUsers,
    events.origEvents,
    igdbIdsByDbId,
    gen,
  );
  await reassignEventCreators(
    svc.database,
    events.origEvents,
    events.genEvents,
    allUsers as { id: number; username: string; role: string }[],
    ROLE_ACCOUNTS[0].username,
  );
  await svc.settings.setDemoMode(true);
}

/** Build final counts DTO. */
function buildCounts(
  allUsers: UserRow[],
  events: { createdEvents: EventRow[] },
  chars: { createdChars: CharRow[] },
  signups: SignupRow[],
  gen: GeneratedData,
): DemoDataCountsDto {
  return {
    users: allUsers.length,
    events: events.createdEvents.length,
    characters: chars.createdChars.length,
    signups: signups.length,
    availability: gen.avail.length,
    gameTimeSlots: gen.gameTime.length,
    notifications: gen.notifs.length,
  };
}

/** Create seed admin + all fake gamers. */
async function createUsers(svc: DemoDataService) {
  const db = svc.database;
  const [seedAdmin] = await db
    .insert(schema.users)
    .values({ username: 'SeedAdmin', role: 'admin' })
    .returning();
  const gamerValues = FAKE_GAMERS.map((g) => ({
    username: g.username,
    avatar: g.avatar,
    role: 'member' as const,
  }));
  const insertedGamers = (await svc.batchInsertReturning(
    schema.users,
    gamerValues,
  )) as UserRow[];
  const allUsers = [seedAdmin, ...insertedGamers];
  const userByName = new Map(allUsers.map((u) => [u.username, u]));
  return { seedAdmin, allUsers, userByName };
}

/** Map event definition to insert value. */
function mapEventValue(
  e: {
    title: string;
    description: string;
    gameId: number | null;
    startTime: Date;
    endTime: Date;
    maxPlayers?: number | null;
  },
  creatorId: number,
): Record<string, unknown> {
  return {
    title: e.title,
    description: e.description,
    gameId: e.gameId,
    creatorId,
    duration: [e.startTime, e.endTime] as [Date, Date],
    ...(e.maxPlayers != null ? { maxAttendees: e.maxPlayers } : {}),
  };
}

/** Insert both original and generated events. */
async function insertEvents(
  svc: DemoDataService,
  seedAdminId: number,
  allGames: GameRow[],
  generatedEvents: ReturnType<typeof generateEvents>,
) {
  const origDefs = getEventsDefinitions(allGames);
  const origValues = origDefs.map((e) => mapEventValue(e, seedAdminId));
  const genValues = generatedEvents.map((e) => mapEventValue(e, seedAdminId));
  const created = (await svc.batchInsertReturning(schema.events, [
    ...origValues,
    ...genValues,
  ])) as EventRow[];
  return {
    createdEvents: created,
    origEvents: created.slice(0, origDefs.length),
    genEvents: created.slice(origDefs.length),
  };
}

/** Build char-by-user-game lookup from created characters. */
function buildCharByUserGame(created: CharRow[]): Map<string, string> {
  const map = new Map<string, string>();
  for (const c of created) {
    const key = `${c.userId}:${c.gameId}`;
    if (!map.has(key) || c.isMain) map.set(key, c.id);
  }
  return map;
}

/** Insert both original and generated characters. */
async function insertCharacters(
  svc: DemoDataService,
  userByName: Map<string, { id: number }>,
  allGames: { id: number }[],
  generatedChars: ReturnType<typeof generateCharacters>,
) {
  const gamesBySlug = new Map((allGames as GameRow[]).map((g) => [g.slug, g]));
  const origValues = buildOriginalCharValues(
    CHARACTERS_CONFIG,
    userByName,
    allGames,
    getClassIconUrl,
  );
  const genValues = buildGeneratedCharValues(
    generatedChars,
    userByName,
    gamesBySlug,
    getClassIconUrl,
  );
  const created = (await svc.batchInsertReturning(schema.characters, [
    ...origValues,
    ...genValues,
  ])) as CharRow[];
  return {
    createdChars: created,
    charByUserGame: buildCharByUserGame(created),
  };
}

/** Insert both original and generated signups, deduped. */
async function insertSignups(
  svc: DemoDataService,
  events: { origEvents: EventRow[]; genEvents: EventRow[] },
  allUsers: { id: number; role: string }[],
  userByName: Map<string, { id: number }>,
  charByUserGame: Map<string, string>,
  generatedSignups: ReturnType<typeof generateSignups>,
) {
  const origValues = buildOriginalSignupValues(
    events.origEvents,
    allUsers,
    charByUserGame,
  );
  const genValues = buildGeneratedSignupValues(
    generatedSignups,
    events.genEvents,
    userByName,
    charByUserGame,
  );
  const unique = dedupeByKey(
    [...origValues, ...genValues],
    (s) => `${String(s.eventId)}:${String(s.userId)}`,
  );
  return (await svc.batchInsertReturning(
    schema.eventSignups,
    unique,
  )) as SignupRow[];
}

/** Insert roster assignments. */
async function insertRoster(
  svc: DemoDataService,
  signups: SignupRow[],
  events: { createdEvents: EventRow[]; genEvents: EventRow[] },
  chars: { createdChars: CharRow[] },
  gen: GeneratedData,
  allGames: GameRow[],
): Promise<void> {
  const values = buildRosterValues({
    createdSignups: signups,
    createdEvents: events.createdEvents,
    createdChars: chars.createdChars,
    generatedEvents: gen.events,
    genEvents: events.genEvents,
    allGames,
  });
  if (values.length > 0)
    await svc.batchInsert(schema.rosterAssignments, values);
}
