/**
 * Talent positions for caster classes: Druid, Mage, Priest, Warlock.
 * See classic-talent-positions.ts for format documentation.
 */
import type { ClassPositionMap } from './types';

/** Druid talent tree positions */
export const DRUID_POSITIONS: ClassPositionMap = {
    Balance: {
        'starlight-wrath': 'a1',
        'natures-grasp': 'a2',
        'improved-natures-grasp': 'a3',
        'control-of-nature': 'b1',
        'focused-starlight': 'b2',
        'improved-moonfire': 'b3',
        'brambles': 'c1',
        'insect-swarm': 'c3',
        'natures-reach': 'c4',
        'vengeance': 'd2',
        'celestial-focus': 'd3',
        'lunar-guidance': 'e1',
        'natures-grace': 'e2',
        'moonglow': 'e3',
        'moonfury': 'f2',
        'balance-of-power': 'f3',
        'dreamstate': 'g1',
        'moonkin-form': 'g2',
        'improved-faerie-fire': 'g3',
        'wrath-of-cenarius': 'h2',
        'force-of-nature': 'i2',
    },
    'Feral Combat': {
        'ferocity': 'a2',
        'feral-aggression': 'a3',
        'feral-instinct': 'b1',
        'brutal-impact': 'b2',
        'thick-hide': 'b3',
        'feral-swiftness': 'c1',
        'feral-charge': 'c2',
        'sharpened-claws': 'c3',
        'shredding-attacks': 'd1',
        'predatory-strikes': 'd2',
        'primal-fury': 'd3',
        'savage-fury': 'e1',
        'faerie-fire-feral': 'e3',
        'nurturing-instinct': 'e4',
        'heart-of-the-wild': 'f2',
        'survival-of-the-fittest': 'f3',
        'primal-tenacity': 'g1',
        'leader-of-the-pack': 'g2',
        'improved-leader-of-the-pack': 'g3',
        'predatory-instincts': 'h3',
        'mangle': 'i2',
    },
    Restoration: {
        'improved-mark-of-the-wild': 'a2',
        'furor': 'a3',
        'naturalist': 'b1',
        'natures-focus': 'b2',
        'natural-shapeshifter': 'b3',
        'intensity': 'c1',
        'subtlety': 'c2',
        'omen-of-clarity': 'c3',
        'tranquil-spirit': 'd2',
        'improved-rejuvenation': 'd3',
        'natures-swiftness': 'e1',
        'gift-of-nature': 'e2',
        'improved-tranquility': 'e4',
        'empowered-touch': 'f1',
        'improved-regrowth': 'f3',
        'living-spirit': 'g1',
        'swiftmend': 'g2',
        'natural-perfection': 'g3',
        'empowered-rejuvenation': 'h2',
        'tree-of-life': 'i2',
    },
};

/** Mage talent tree positions */
export const MAGE_POSITIONS: ClassPositionMap = {
    Arcane: {
        'arcane-subtlety': 'a1',
        'arcane-focus': 'a2',
        'improved-arcane-missiles': 'a3',
        'wand-specialization': 'b1',
        'magic-absorption': 'b2',
        'arcane-concentration': 'b3',
        'magic-attunement': 'c1',
        'arcane-impact': 'c2',
        'arcane-fortitude': 'c4',
        'improved-mana-shield': 'd1',
        'improved-counterspell': 'd2',
        'arcane-meditation': 'd4',
        'improved-blink': 'e1',
        'presence-of-mind': 'e2',
        'arcane-mind': 'e4',
        'prismatic-cloak': 'f1',
        'arcane-instability': 'f2',
        'arcane-potency': 'f3',
        'empowered-arcane-missiles': 'g1',
        'arcane-power': 'g2',
        'spell-power': 'g3',
        'mind-mastery': 'h2',
        'slow': 'i2',
    },
    Fire: {
        'improved-fireball': 'a2',
        'impact': 'a3',
        'ignite': 'b1',
        'flame-throwing': 'b2',
        'improved-fire-blast': 'b3',
        'incineration': 'c1',
        'improved-flamestrike': 'c2',
        'pyroblast': 'c3',
        'burning-soul': 'c4',
        'improved-scorch': 'd1',
        'molten-shields': 'd2',
        'master-of-elements': 'd4',
        'playing-with-fire': 'e1',
        'critical-mass': 'e2',
        'blast-wave': 'e3',
        'blazing-speed': 'f1',
        'fire-power': 'f3',
        'pyromaniac': 'g1',
        'combustion': 'g2',
        'molten-fury': 'g3',
        'empowered-fireball': 'h3',
        'dragons-breath': 'i2',
    },
    Frost: {
        'frost-warding': 'a1',
        'improved-frostbolt': 'a2',
        'elemental-precision': 'a3',
        'ice-shards': 'b1',
        'frostbite': 'b2',
        'improved-frost-nova': 'b3',
        'permafrost': 'b4',
        'piercing-ice': 'c1',
        'icy-veins': 'c2',
        'improved-blizzard': 'c4',
        'arctic-reach': 'd1',
        'frost-channeling': 'd2',
        'shatter': 'd3',
        'frozen-core': 'e1',
        'cold-snap': 'e2',
        'improved-cone-of-cold': 'e3',
        'ice-floes': 'f1',
        'winters-chill': 'f3',
        'ice-barrier': 'g2',
        'arctic-winds': 'g3',
        'empowered-frostbolt': 'h2',
        'summon-water-elemental': 'i2',
    },
};

/** Priest talent tree positions */
export const PRIEST_POSITIONS: ClassPositionMap = {
    Discipline: {
        'unbreakable-will': 'a2',
        'wand-specialization': 'a3',
        'silent-resolve': 'b1',
        'improved-power-word-fortitude': 'b2',
        'improved-power-word-shield': 'b3',
        'martyrdom': 'b4',
        'absolution': 'c1',
        'inner-focus': 'c2',
        'meditation': 'c3',
        'improved-inner-fire': 'd1',
        'mental-agility': 'd2',
        'improved-mana-burn': 'd4',
        'mental-strength': 'e2',
        'divine-spirit': 'e3',
        'improved-divine-spirit': 'e4',
        'focused-power': 'f1',
        'force-of-will': 'f3',
        'focused-will': 'g1',
        'power-infusion': 'g2',
        'reflective-shield': 'g3',
        'enlightenment': 'h2',
        'pain-suppression': 'i2',
    },
    Holy: {
        'healing-focus': 'a1',
        'improved-renew': 'a2',
        'holy-specialization': 'a3',
        'spell-warding': 'b2',
        'divine-fury': 'b3',
        'holy-nova': 'c1',
        'blessed-recovery': 'c2',
        'inspiration': 'c4',
        'holy-reach': 'd1',
        'improved-healing': 'd2',
        'searing-light': 'd3',
        'healing-prayers': 'e1',
        'spirit-of-redemption': 'e2',
        'spiritual-guidance': 'e3',
        'surge-of-light': 'f1',
        'spiritual-healing': 'f3',
        'holy-concentration': 'g1',
        'lightwell': 'g2',
        'blessed-resilience': 'g3',
        'empowered-healing': 'h2',
        'circle-of-healing': 'i2',
    },
    Shadow: {
        'spirit-tap': 'a2',
        'blackout': 'a3',
        'shadow-affinity': 'b1',
        'improved-shadow-word-pain': 'b2',
        'shadow-focus': 'b3',
        'improved-psychic-scream': 'c1',
        'improved-mind-blast': 'c2',
        'mind-flay': 'c3',
        'improved-fade': 'd2',
        'shadow-reach': 'd3',
        'shadow-weaving': 'd4',
        'silence': 'e1',
        'vampiric-embrace': 'e2',
        'improved-vampiric-embrace': 'e3',
        'focused-mind': 'e4',
        'shadow-resilience': 'f1',
        'darkness': 'f3',
        'shadowform': 'g2',
        'shadow-power': 'g3',
        'misery': 'h3',
        'vampiric-touch': 'i2',
    },
};

/** Warlock talent tree positions */
export const WARLOCK_POSITIONS: ClassPositionMap = {
    Affliction: {
        'suppression': 'a2',
        'improved-corruption': 'a3',
        'improved-curse-of-weakness': 'b1',
        'improved-drain-soul': 'b2',
        'improved-life-tap': 'b3',
        'soul-siphon': 'b4',
        'improved-curse-of-agony': 'c1',
        'fel-concentration': 'c2',
        'amplify-curse': 'c3',
        'grim-reach': 'd1',
        'nightfall': 'd2',
        'empowered-corruption': 'd4',
        'shadow-embrace': 'e1',
        'siphon-life': 'e2',
        'curse-of-exhaustion': 'e3',
        'shadow-mastery': 'f2',
        'contagion': 'g2',
        'dark-pact': 'g3',
        'improved-howl-of-terror': 'h1',
        'malediction': 'h3',
        'unstable-affliction': 'i2',
    },
    Demonology: {
        'improved-healthstone': 'a1',
        'improved-imp': 'a2',
        'demonic-embrace': 'a3',
        'improved-health-funnel': 'b1',
        'improved-voidwalker': 'b2',
        'fel-intellect': 'b3',
        'improved-sayaad': 'c1',
        'fel-domination': 'c2',
        'fel-stamina': 'c3',
        'demonic-aegis': 'c4',
        'master-summoner': 'd2',
        'unholy-power': 'd3',
        'improved-subjugate-demon': 'e1',
        'demonic-sacrifice': 'e2',
        'master-conjuror': 'e4',
        'mana-feed': 'f1',
        'master-demonologist': 'f3',
        'demonic-resilience': 'g1',
        'soul-link': 'g2',
        'demonic-knowledge': 'g3',
        'demonic-tactics': 'h2',
        'summon-felguard': 'i2',
    },
    Destruction: {
        'improved-shadow-bolt': 'a2',
        'cataclysm': 'a3',
        'bane': 'b2',
        'aftermath': 'b3',
        'improved-firebolt': 'c1',
        'improved-lash-of-pain': 'c2',
        'devastation': 'c3',
        'shadowburn': 'c4',
        'intensity': 'd1',
        'destructive-reach': 'd2',
        'improved-searing-pain': 'd4',
        'pyroclasm': 'e1',
        'improved-immolate': 'e2',
        'ruin': 'e3',
        'nether-protection': 'f1',
        'emberstorm': 'f3',
        'backlash': 'g1',
        'conflagrate': 'g2',
        'soul-leech': 'g3',
        'shadow-and-flame': 'h2',
        'shadowfury': 'i2',
    },
};
