/**
 * Talent positions for hybrid class: Shaman.
 * See classic-talent-positions.ts for format documentation.
 */
import type { ClassPositionMap } from './types';

/** Shaman talent tree positions */
export const SHAMAN_POSITIONS: ClassPositionMap = {
    Elemental: {
        'convection': 'a2',
        'concussion': 'a3',
        'earths-grasp': 'b1',
        'elemental-warding': 'b2',
        'call-of-flame': 'b3',
        'elemental-focus': 'c1',
        'reverberation': 'c2',
        'call-of-thunder': 'c3',
        'improved-fire-totems': 'd1',
        'eye-of-the-storm': 'd2',
        'elemental-devastation': 'd4',
        'storm-reach': 'e1',
        'elemental-fury': 'e2',
        'unrelenting-storm': 'e4',
        'elemental-precision': 'f1',
        'lightning-mastery': 'f3',
        'elemental-mastery': 'g2',
        'elemental-shields': 'g3',
        'lightning-overload': 'h2',
        'totem-of-wrath': 'i2',
    },
    Enhancement: {
        'ancestral-knowledge': 'a2',
        'shield-specialization': 'a3',
        'guardian-totems': 'b1',
        'thundering-strikes': 'b2',
        'improved-ghost-wolf': 'b3',
        'improved-lightning-shield': 'b4',
        'enhancing-totems': 'c1',
        'shamanistic-focus': 'c3',
        'anticipation': 'c4',
        'flurry': 'd2',
        'toughness': 'd3',
        'improved-weapon-totems': 'e1',
        'spirit-weapons': 'e2',
        'elemental-weapons': 'e3',
        'mental-quickness': 'f1',
        'weapon-mastery': 'f4',
        'dual-wield-specialization': 'g1',
        'dual-wield': 'g2',
        'stormstrike': 'g3',
        'unleashed-rage': 'h2',
        'shamanistic-rage': 'i2',
    },
    Restoration: {
        'improved-healing-wave': 'a2',
        'tidal-focus': 'a3',
        'improved-reincarnation': 'b1',
        'ancestral-healing': 'b2',
        'totemic-focus': 'b3',
        'natures-guidance': 'c1',
        'healing-focus': 'c2',
        'totemic-mastery': 'c3',
        'healing-grace': 'c4',
        'restorative-totems': 'd2',
        'tidal-mastery': 'd3',
        'healing-way': 'e1',
        'natures-swiftness': 'e3',
        'focused-mind': 'e4',
        'purification': 'f3',
        'mana-tide-totem': 'g2',
        'natures-guardian': 'g3',
        'natures-blessing': 'h2',
        'improved-chain-heal': 'h3',
        'earth-shield': 'i2',
    },
};
