/**
 * Talent positions for melee classes: Hunter, Paladin, Rogue, Warrior.
 * See classic-talent-positions.ts for format documentation.
 */
import type { ClassPositionMap } from './types';

/** Hunter talent tree positions */
export const HUNTER_POSITIONS: ClassPositionMap = {
    'Beast Mastery': {
        'improved-aspect-of-the-hawk': 'a2',
        'endurance-training': 'a3',
        'focused-fire': 'b1',
        'improved-aspect-of-the-monkey': 'b2',
        'thick-hide': 'b3',
        'improved-revive-pet': 'b4',
        'pathfinding': 'c1',
        'bestial-swiftness': 'c2',
        'unleashed-fury': 'c3',
        'improved-mend-pet': 'd2',
        'ferocity': 'd3',
        'spirit-bond': 'e1',
        'intimidation': 'e2',
        'bestial-discipline': 'e4',
        'animal-handler': 'f1',
        'frenzy': 'f3',
        'ferocious-inspiration': 'g1',
        'bestial-wrath': 'g2',
        'catlike-reflexes': 'g3',
        'serpents-swiftness': 'h3',
        'the-beast-within': 'i2',
    },
    Marksmanship: {
        'improved-concussive-shot': 'a2',
        'lethal-shots': 'a3',
        'go-for-the-throat': 'c1',
        'improved-hunters-mark': 'b2',
        'efficiency': 'b3',
        'improved-arcane-shot': 'c2',
        'aimed-shot': 'c3',
        'rapid-killing': 'c4',
        'improved-stings': 'd2',
        'mortal-shots': 'd3',
        'concussive-barrage': 'e1',
        'scatter-shot': 'e2',
        'barrage': 'e3',
        'combat-experience': 'f1',
        'ranged-weapon-specialization': 'f4',
        'careful-aim': 'g1',
        'trueshot-aura': 'g2',
        'improved-barrage': 'g3',
        'master-marksman': 'h2',
        'silencing-shot': 'i2',
    },
    Survival: {
        'monster-slaying': 'a1',
        'humanoid-slaying': 'a2',
        'hawk-eye': 'a3',
        'savage-strikes': 'a4',
        'entrapment': 'b1',
        'deflection': 'b2',
        'improved-wing-clip': 'b3',
        'clever-traps': 'c1',
        'survivalist': 'c2',
        'deterrence': 'c3',
        'trap-mastery': 'd1',
        'surefooted': 'd2',
        'improved-feign-death': 'd4',
        'survival-instincts': 'e1',
        'killer-instinct': 'e2',
        'counterattack': 'e3',
        'resourcefulness': 'f1',
        'lightning-reflexes': 'f3',
        'thrill-of-the-hunt': 'g1',
        'wyvern-sting': 'g2',
        'expose-weakness': 'g3',
        'master-tactician': 'h2',
        'readiness': 'i2',
    },
};

/** Paladin talent tree positions */
export const PALADIN_POSITIONS: ClassPositionMap = {
    Holy: {
        'divine-strength': 'a2',
        'divine-intellect': 'a3',
        'spiritual-focus': 'b2',
        'improved-seal-of-righteousness': 'b3',
        'healing-light': 'c1',
        'aura-mastery': 'c2',
        'improved-lay-on-hands': 'c3',
        'unyielding-faith': 'c4',
        'illumination': 'd2',
        'improved-blessing-of-wisdom': 'd3',
        'pure-of-heart': 'e1',
        'divine-favor': 'e2',
        'sanctified-light': 'e3',
        'purifying-power': 'f1',
        'holy-power': 'f3',
        'lights-grace': 'g1',
        'holy-shock': 'g2',
        'blessed-life': 'g3',
        'holy-guidance': 'h2',
        'divine-illumination': 'i2',
    },
    Protection: {
        'improved-devotion-aura': 'a2',
        'redoubt': 'a3',
        'precision': 'b1',
        'guardians-favor': 'b2',
        'toughness': 'b4',
        'blessing-of-kings': 'c1',
        'improved-righteous-fury': 'c2',
        'shield-specialization': 'c3',
        'anticipation': 'c4',
        'stoicism': 'd1',
        'improved-hammer-of-justice': 'd2',
        'improved-concentration-aura': 'd3',
        'spell-warding': 'e1',
        'blessing-of-sanctuary': 'e2',
        'reckoning': 'e3',
        'sacred-duty': 'f1',
        'one-handed-weapon-specialization': 'f3',
        'improved-holy-shield': 'g1',
        'holy-shield': 'g2',
        'ardent-defender': 'g3',
        'combat-expertise': 'h3',
        'avengers-shield': 'i2',
    },
    Retribution: {
        'improved-blessing-of-might': 'a2',
        'benediction': 'a3',
        'improved-judgement': 'b1',
        'improved-seal-of-the-crusader': 'b2',
        'deflection': 'b3',
        'vindication': 'c1',
        'conviction': 'c2',
        'seal-of-command': 'c3',
        'pursuit-of-justice': 'c4',
        'eye-for-an-eye': 'd1',
        'improved-retribution-aura': 'd3',
        'crusade': 'd4',
        'two-handed-weapon-specialization': 'e1',
        'sanctity-aura': 'e3',
        'improved-sanctity-aura': 'e4',
        'vengeance': 'f2',
        'sanctified-judgement': 'f3',
        'sanctified-seals': 'g1',
        'repentance': 'g2',
        'divine-purpose': 'g3',
        'fanaticism': 'h2',
        'crusader-strike': 'i2',
    },
};

/** Rogue talent tree positions */
export const ROGUE_POSITIONS: ClassPositionMap = {
    Assassination: {
        'improved-eviscerate': 'a1',
        'remorseless-attacks': 'a2',
        'malice': 'a3',
        'ruthlessness': 'b1',
        'murder': 'b2',
        'puncturing-wounds': 'b4',
        'relentless-strikes': 'c1',
        'improved-expose-armor': 'c2',
        'lethality': 'c3',
        'vile-poisons': 'd2',
        'improved-poisons': 'd3',
        'fleet-footed': 'e1',
        'cold-blood': 'e2',
        'improved-kidney-shot': 'e3',
        'quick-recovery': 'e4',
        'seal-fate': 'f2',
        'master-poisoner': 'f3',
        'deadened-nerves': 'g3',
        'vigor': 'g2',
        'find-weakness': 'h3',
        'mutilate': 'i2',
    },
    Combat: {
        'improved-gouge': 'a1',
        'improved-sinister-strike': 'a2',
        'lightning-reflexes': 'a3',
        'improved-slice-and-dice': 'b1',
        'deflection': 'b2',
        'precision': 'b3',
        'endurance': 'c1',
        'riposte': 'c2',
        'improved-sprint': 'c4',
        'improved-kick': 'd1',
        'dagger-specialization': 'd2',
        'dual-wield-specialization': 'd3',
        'mace-specialization': 'e1',
        'blade-flurry': 'e2',
        'sword-specialization': 'e3',
        'fist-weapon-specialization': 'e4',
        'blade-twisting': 'f1',
        'weapon-expertise': 'f2',
        'aggression': 'f3',
        'vitality': 'g1',
        'adrenaline-rush': 'g2',
        'nerves-of-steel': 'g3',
        'combat-potency': 'h3',
        'surprise-attacks': 'i2',
    },
    Subtlety: {
        'master-of-deception': 'a2',
        'opportunity': 'a3',
        'sleight-of-hand': 'b1',
        'dirty-tricks': 'b2',
        'camouflage': 'b3',
        'initiative': 'c1',
        'ghostly-strike': 'c2',
        'improved-ambush': 'c3',
        'setup': 'd1',
        'elusiveness': 'd2',
        'serrated-blades': 'd3',
        'heightened-senses': 'e1',
        'preparation': 'e2',
        'dirty-deeds': 'e3',
        'hemorrhage': 'e4',
        'master-of-subtlety': 'f1',
        'deadliness': 'f3',
        'enveloping-shadows': 'g1',
        'premeditation': 'g2',
        'cheat-death': 'g3',
        'sinister-calling': 'h2',
        'shadowstep': 'i2',
    },
};

/** Warrior talent tree positions */
export const WARRIOR_POSITIONS: ClassPositionMap = {
    Arms: {
        'improved-heroic-strike': 'a1',
        'deflection': 'a2',
        'improved-rend': 'a3',
        'improved-charge': 'b1',
        'iron-will': 'b2',
        'improved-thunder-clap': 'b3',
        'improved-overpower': 'c1',
        'anger-management': 'c2',
        'deep-wounds': 'c3',
        'two-handed-weapon-specialization': 'd2',
        'impale': 'd3',
        'poleaxe-specialization': 'e1',
        'death-wish': 'e2',
        'mace-specialization': 'e3',
        'sword-specialization': 'e4',
        'improved-intercept': 'f1',
        'improved-hamstring': 'f3',
        'improved-disciplines': 'f4',
        'blood-frenzy': 'g1',
        'mortal-strike': 'g2',
        'second-wind': 'g3',
        'improved-mortal-strike': 'h2',
        'endless-rage': 'i2',
    },
    Fury: {
        'booming-voice': 'a2',
        'cruelty': 'a3',
        'improved-demoralizing-shout': 'b2',
        'unbridled-wrath': 'b3',
        'improved-cleave': 'c1',
        'piercing-howl': 'c2',
        'blood-craze': 'c3',
        'commanding-presence': 'c4',
        'dual-wield-specialization': 'd1',
        'improved-execute': 'd2',
        'enrage': 'd3',
        'improved-slam': 'e1',
        'sweeping-strikes': 'e2',
        'weapon-mastery': 'e4',
        'improved-berserker-rage': 'f1',
        'flurry': 'f3',
        'precision': 'g1',
        'bloodthirst': 'g2',
        'improved-whirlwind': 'g3',
        'improved-berserker-stance': 'h3',
        'rampage': 'i2',
    },
    Protection: {
        'improved-bloodrage': 'a1',
        'tactical-mastery': 'a2',
        'anticipation': 'a3',
        'shield-specialization': 'b2',
        'toughness': 'b3',
        'last-stand': 'c1',
        'improved-shield-block': 'c2',
        'improved-revenge': 'c3',
        'defiance': 'c4',
        'improved-sunder-armor': 'd1',
        'improved-disarm': 'd2',
        'improved-taunt': 'd3',
        'improved-shield-wall': 'e1',
        'concussion-blow': 'e2',
        'improved-shield-bash': 'e3',
        'shield-mastery': 'f1',
        'one-handed-weapon-specialization': 'f3',
        'improved-defensive-stance': 'g1',
        'shield-slam': 'g2',
        'focused-rage': 'g3',
        'vitality': 'h2',
        'devastate': 'i2',
    },
};
