/**
 * Static instance data for Classic WoW dungeons and raids.
 * Extracted from blizzard.service.ts for file size compliance (ROK-711).
 */
import type { SubInstance } from './blizzard.constants';

/**
 * Classic dungeon complexes that should be expanded into their individual wings.
 * The retail journal combines these, but Classic has them as separate instances.
 * Key = parent instance name (must match Blizzard journal name exactly).
 */
export const CLASSIC_SUB_INSTANCES: Record<string, SubInstance[]> = {
  'Scarlet Monastery': [
    { idSuffix: 1, name: 'SM: Graveyard', shortName: 'SM:GY', minimumLevel: 26, maximumLevel: 32 },
    { idSuffix: 2, name: 'SM: Library', shortName: 'SM:Lib', minimumLevel: 29, maximumLevel: 33 },
    { idSuffix: 3, name: 'SM: Armory', shortName: 'SM:Arm', minimumLevel: 32, maximumLevel: 36 },
    { idSuffix: 4, name: 'SM: Cathedral', shortName: 'SM:Cath', minimumLevel: 34, maximumLevel: 40 },
  ],
  Maraudon: [
    { idSuffix: 1, name: 'Maraudon: Purple', shortName: 'Mara:P', minimumLevel: 40, maximumLevel: 49 },
    { idSuffix: 2, name: 'Maraudon: Orange', shortName: 'Mara:O', minimumLevel: 40, maximumLevel: 49 },
    { idSuffix: 3, name: 'Maraudon: Pristine Waters', shortName: 'Mara:PW', minimumLevel: 46, maximumLevel: 55 },
  ],
};

/** Instance short names for display */
export const INSTANCE_SHORT_NAMES: Record<string, string> = {
  'Ragefire Chasm': 'RFC',
  'Wailing Caverns': 'WC',
  Deadmines: 'DM',
  'Shadowfang Keep': 'SFK',
  'The Stockade': 'Stocks',
  'Blackfathom Deeps': 'BFD',
  Gnomeregan: 'Gnomer',
  'Scarlet Halls': 'SH',
  'Razorfen Kraul': 'RFK',
  'Razorfen Downs': 'RFD',
  Uldaman: 'Ulda',
  "Zul'Farrak": 'ZF',
  "The Temple of Atal'hakkar": 'ST',
  'Blackrock Depths': 'BRD',
  'Lower Blackrock Spire': 'LBRS',
  'Upper Blackrock Spire': 'UBRS',
  'Dire Maul - Capital Gardens': 'DM:N',
  'Dire Maul - Gordok Commons': 'DM:N',
  'Dire Maul - Warpwood Quarter': 'DM:W',
  'Stratholme - Main Gate': 'Strat:UD',
  'Stratholme - Service Entrance': 'Strat:Live',
  Scholomance: 'Scholo',
  'Molten Core': 'MC',
  'Blackwing Lair': 'BWL',
  "Ruins of Ahn'Qiraj": 'AQ20',
  "Temple of Ahn'Qiraj": 'AQ40',
  'Onyxia\'s Lair': 'Ony',
  'Hellfire Ramparts': 'Ramps',
  'The Blood Furnace': 'BF',
  'The Slave Pens': 'SP',
  'The Underbog': 'UB',
  'Mana-Tombs': 'MT',
  'Auchenai Crypts': 'AC',
  'Old Hillsbrad Foothills': 'OHF',
  'Sethekk Halls': 'Seth',
  'The Steamvault': 'SV',
  'Shadow Labyrinth': 'SL',
  'The Shattered Halls': 'SHH',
  'The Mechanar': 'Mech',
  'The Botanica': 'Bot',
  'The Arcatraz': 'Arc',
  'The Black Morass': 'BM',
  "Magisters' Terrace": 'MgT',
  Karazhan: 'Kara',
  "Gruul's Lair": 'Gruul',
  "Magtheridon's Lair": 'Mag',
  'Serpentshrine Cavern': 'SSC',
  'The Eye': 'TK',
  'Hyjal Summit': 'Hyjal',
  'Black Temple': 'BT',
  "Zul'Aman": 'ZA',
  'Sunwell Plateau': 'SWP',
  'Utgarde Keep': 'UK',
  'The Nexus': 'Nex',
  'Azjol-Nerub': 'AN',
  "Ahn'kahet: The Old Kingdom": 'OK',
  "Drak'Tharon Keep": 'DTK',
  'The Violet Hold': 'VH',
  Gundrak: 'GD',
  'Halls of Stone': 'HoS',
  'Halls of Lightning': 'HoL',
  'The Oculus': 'Ocu',
  'The Culling of Stratholme': 'CoS',
  'Utgarde Pinnacle': 'UP',
  'Trial of the Champion': 'ToC5',
  'The Forge of Souls': 'FoS',
  'Pit of Saron': 'PoS',
  'Halls of Reflection': 'HoR',
  Naxxramas: 'Naxx',
  'The Obsidian Sanctum': 'OS',
  'The Eye of Eternity': 'EoE',
  'Vault of Archavon': 'VoA',
  Ulduar: 'Uld',
  'Trial of the Crusader': 'ToC',
  'Icecrown Citadel': 'ICC',
  'Ruby Sanctum': 'RS',
};

/** Get the short name for an instance, falling back to the full name. */
export function getShortName(name: string): string {
  return INSTANCE_SHORT_NAMES[name] ?? name;
}

/** Classic instance level ranges (accurate per-expansion data). */
export const CLASSIC_INSTANCE_LEVELS: Record<
  string,
  { minimumLevel: number; maximumLevel: number }
> = {
  'Ragefire Chasm': { minimumLevel: 13, maximumLevel: 18 },
  'Wailing Caverns': { minimumLevel: 17, maximumLevel: 24 },
  Deadmines: { minimumLevel: 17, maximumLevel: 26 },
  'Shadowfang Keep': { minimumLevel: 22, maximumLevel: 30 },
  'The Stockade': { minimumLevel: 22, maximumLevel: 30 },
  'Blackfathom Deeps': { minimumLevel: 24, maximumLevel: 32 },
  Gnomeregan: { minimumLevel: 29, maximumLevel: 38 },
  'Scarlet Halls': { minimumLevel: 28, maximumLevel: 38 },
  'Razorfen Kraul': { minimumLevel: 30, maximumLevel: 40 },
  'Razorfen Downs': { minimumLevel: 40, maximumLevel: 50 },
  Uldaman: { minimumLevel: 42, maximumLevel: 52 },
  "Zul'Farrak": { minimumLevel: 44, maximumLevel: 54 },
  "The Temple of Atal'hakkar": { minimumLevel: 50, maximumLevel: 56 },
  'Blackrock Depths': { minimumLevel: 52, maximumLevel: 60 },
  'Lower Blackrock Spire': { minimumLevel: 55, maximumLevel: 60 },
  'Dire Maul - Capital Gardens': { minimumLevel: 55, maximumLevel: 60 },
  'Dire Maul - Gordok Commons': { minimumLevel: 55, maximumLevel: 60 },
  'Dire Maul - Warpwood Quarter': { minimumLevel: 55, maximumLevel: 60 },
  'Stratholme - Main Gate': { minimumLevel: 58, maximumLevel: 60 },
  'Stratholme - Service Entrance': { minimumLevel: 58, maximumLevel: 60 },
  Scholomance: { minimumLevel: 58, maximumLevel: 60 },
  'Molten Core': { minimumLevel: 60, maximumLevel: 60 },
  'Blackwing Lair': { minimumLevel: 60, maximumLevel: 60 },
  "Ruins of Ahn'Qiraj": { minimumLevel: 60, maximumLevel: 60 },
  "Temple of Ahn'Qiraj": { minimumLevel: 60, maximumLevel: 60 },
  'Hellfire Ramparts': { minimumLevel: 60, maximumLevel: 62 },
  'The Blood Furnace': { minimumLevel: 61, maximumLevel: 63 },
  'The Slave Pens': { minimumLevel: 62, maximumLevel: 64 },
  'The Underbog': { minimumLevel: 63, maximumLevel: 65 },
  'Mana-Tombs': { minimumLevel: 64, maximumLevel: 66 },
  'Auchenai Crypts': { minimumLevel: 65, maximumLevel: 67 },
  'Old Hillsbrad Foothills': { minimumLevel: 66, maximumLevel: 68 },
  'Sethekk Halls': { minimumLevel: 67, maximumLevel: 69 },
  'The Steamvault': { minimumLevel: 68, maximumLevel: 70 },
  'Shadow Labyrinth': { minimumLevel: 69, maximumLevel: 70 },
  'The Shattered Halls': { minimumLevel: 69, maximumLevel: 70 },
  'The Mechanar': { minimumLevel: 69, maximumLevel: 70 },
  'The Botanica': { minimumLevel: 69, maximumLevel: 70 },
  'The Arcatraz': { minimumLevel: 69, maximumLevel: 70 },
  'The Black Morass': { minimumLevel: 69, maximumLevel: 70 },
  "Magisters' Terrace": { minimumLevel: 70, maximumLevel: 70 },
  Karazhan: { minimumLevel: 70, maximumLevel: 70 },
  "Gruul's Lair": { minimumLevel: 70, maximumLevel: 70 },
  "Magtheridon's Lair": { minimumLevel: 70, maximumLevel: 70 },
  'Serpentshrine Cavern': { minimumLevel: 70, maximumLevel: 70 },
  'The Eye': { minimumLevel: 70, maximumLevel: 70 },
  'Hyjal Summit': { minimumLevel: 70, maximumLevel: 70 },
  'Black Temple': { minimumLevel: 70, maximumLevel: 70 },
  "Zul'Aman": { minimumLevel: 70, maximumLevel: 70 },
  'Sunwell Plateau': { minimumLevel: 70, maximumLevel: 70 },
  'Utgarde Keep': { minimumLevel: 69, maximumLevel: 72 },
  'The Nexus': { minimumLevel: 71, maximumLevel: 73 },
  'Azjol-Nerub': { minimumLevel: 72, maximumLevel: 74 },
  "Ahn'kahet: The Old Kingdom": { minimumLevel: 73, maximumLevel: 75 },
  "Drak'Tharon Keep": { minimumLevel: 74, maximumLevel: 76 },
  'The Violet Hold': { minimumLevel: 75, maximumLevel: 77 },
  Gundrak: { minimumLevel: 76, maximumLevel: 78 },
  'Halls of Stone': { minimumLevel: 77, maximumLevel: 79 },
  'Halls of Lightning': { minimumLevel: 78, maximumLevel: 80 },
  'The Oculus': { minimumLevel: 78, maximumLevel: 80 },
  'The Culling of Stratholme': { minimumLevel: 78, maximumLevel: 80 },
  'Utgarde Pinnacle': { minimumLevel: 78, maximumLevel: 80 },
  'Trial of the Champion': { minimumLevel: 80, maximumLevel: 80 },
  'The Forge of Souls': { minimumLevel: 80, maximumLevel: 80 },
  'Pit of Saron': { minimumLevel: 80, maximumLevel: 80 },
  'Halls of Reflection': { minimumLevel: 80, maximumLevel: 80 },
  Naxxramas: { minimumLevel: 80, maximumLevel: 80 },
  'The Obsidian Sanctum': { minimumLevel: 80, maximumLevel: 80 },
  'The Eye of Eternity': { minimumLevel: 80, maximumLevel: 80 },
  'Vault of Archavon': { minimumLevel: 80, maximumLevel: 80 },
  Ulduar: { minimumLevel: 80, maximumLevel: 80 },
  'Trial of the Crusader': { minimumLevel: 80, maximumLevel: 80 },
  'Icecrown Citadel': { minimumLevel: 80, maximumLevel: 80 },
  'Ruby Sanctum': { minimumLevel: 80, maximumLevel: 80 },
  'Blackrock Caverns': { minimumLevel: 80, maximumLevel: 83 },
  'Throne of the Tides': { minimumLevel: 80, maximumLevel: 83 },
  'The Stonecore': { minimumLevel: 81, maximumLevel: 84 },
  'The Vortex Pinnacle': { minimumLevel: 82, maximumLevel: 84 },
  "Lost City of the Tol'vir": { minimumLevel: 83, maximumLevel: 85 },
  'Halls of Origination': { minimumLevel: 83, maximumLevel: 85 },
  'Grim Batol': { minimumLevel: 84, maximumLevel: 85 },
  "Zul'Gurub": { minimumLevel: 85, maximumLevel: 85 },
  'End Time': { minimumLevel: 85, maximumLevel: 85 },
  'Well of Eternity': { minimumLevel: 85, maximumLevel: 85 },
  'Hour of Twilight': { minimumLevel: 85, maximumLevel: 85 },
  'Blackwing Descent': { minimumLevel: 85, maximumLevel: 85 },
  'Bastion of Twilight': { minimumLevel: 85, maximumLevel: 85 },
  'Throne of the Four Winds': { minimumLevel: 85, maximumLevel: 85 },
  'Baradin Hold': { minimumLevel: 85, maximumLevel: 85 },
  Firelands: { minimumLevel: 85, maximumLevel: 85 },
  'Dragon Soul': { minimumLevel: 85, maximumLevel: 85 },
};
